// Źródło danych bloga — docelowo zastąpić fetchemz CMS (Sanity / Contentful / Payload)
// Struktura posta musi odpowiadać schematowi CMS

export type Category = "SEO" | "Opinie" | "Poradnik" | "Wizytówka" | "WordPress" | "Sztuczna Inteligencja";

export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  category: Category;
  date: string;         // ISO: "2025-05-10"
  readTime: number;     // minuty
  coverColor: string;   // kolor placeholdera zanim będzie prawdziwe zdjęcie
  coverImage?: string;  // ścieżka do obrazka w /public
  published: boolean;
  hideFromBlog?: boolean; // widoczny pod URL-em, ale nie listowany na /blog
  pinBottom?: boolean;    // listowany zawsze na końcu /blog (seria lokalizacyjna)
  popular?: boolean;      // wyróżniony jako najpopularniejszy (np. na stronie głównej)
  // Rich snippet dla case study — ocena dotyczy KLIENTA opisanego w artykule
  // (opinie klienta publikowane przez MiauSEO jako stronę trzecią, nie self-review).
  caseRating?: {
    businessName: string; // nazwa opisywanego biznesu (klienta)
    value: number;        // średnia ocena
    count: number;        // liczba opinii
  };
};

export const posts: Post[] = [
  {
    slug: "czym-sa-encje-wizytowka-google-przyklady",
    title: "Czym są encje? Wizytówka Google i przykłady",
    excerpt:
      "Encja to obiekt, który Google identyfikuje niezależnie od słów użytych w zapytaniu. Wyjaśniamy, czym różni się od słowa kluczowego, dlaczego wizytówka jest źródłem danych o encji, a nie encją samą w sobie, jak działa identyfikator MID i pole sameAs. Z gotowym kodem, trzema przykładami z audytów i listą źródeł Google oraz schema.org.",
    category: "SEO",
    date: "2026-09-01",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-encje.svg",
    published: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-warszawa",
    title: "Pozycjonowanie wizytówki Google Warszawa",
    excerpt:
      "W Warszawie nie wygrywa się „całego miasta”. Local Pack rozstrzyga się na poziomie dzielnicy, a często kilku ulic. Jak wyznaczyć swój realny rynek, dlaczego promień działania jest tu krótszy niż gdziekolwiek w Polsce i co zrobić, gdy firma ma kilka punktów.",
    category: "SEO",
    date: "2026-09-01",
    readTime: 13,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-warszawa.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-krakow",
    title: "Pozycjonowanie wizytówki Google Kraków",
    excerpt:
      "Kraków to dwa nakładające się rynki w jednym mieście: mieszkańcy osiedli i ruch turystyczny w obrębie Plant. Jak ustawić profil, żeby obsługiwać oba, co zrobić z opiniami po angielsku i dlaczego adres w centrum bywa pułapką.",
    category: "SEO",
    date: "2026-08-31",
    readTime: 13,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-krakow.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-wroclaw",
    title: "Pozycjonowanie wizytówki Google Wrocław",
    excerpt:
      "Wrocław jest poprzecinany Odrą i jej kanałami, więc odległość w linii prostej rozmija się tu z czasem dojazdu bardziej niż w innych miastach. Co to znaczy dla zasięgu profilu, jak czytać osiedla zamiast dzielnic i gdzie realnie kończy się Twój Local Pack.",
    category: "SEO",
    date: "2026-08-30",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-wroclaw.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-lodz",
    title: "Pozycjonowanie wizytówki Google Łódź",
    excerpt:
      "Łódź to miasto kamienic, podwórek i oficyn, w których pinezka Google potrafi wylądować w zupełnie innym miejscu niż wejście do firmy. Jak poprawić lokalizację, opisać dojście i dlaczego w Łodzi to jest realny czynnik konwersji, a nie kosmetyka.",
    category: "SEO",
    date: "2026-08-29",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-lodz.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-poznan",
    title: "Pozycjonowanie wizytówki Google Poznań",
    excerpt:
      "Poznań ma najbardziej biznesowy profil zapytań spośród dużych polskich miast, a rytm targów na MTP zmienia strukturę wyszukiwań kilka razy w roku. Jak ustawić profil firmy pod klienta B2B i co zrobić z tygodniami targowymi.",
    category: "SEO",
    date: "2026-08-28",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-poznan.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-gdansk",
    title: "Pozycjonowanie wizytówki Google Gdańsk",
    excerpt:
      "Trójmiasto jest jednym organizmem dla mieszkańca i trzema osobnymi rynkami dla algorytmu. Gdzie przebiegają granice widoczności między Gdańskiem, Sopotem i Gdynią, jak obsłużyć klienta z drugiego końca aglomeracji i co robi z tym sezon.",
    category: "SEO",
    date: "2026-08-27",
    readTime: 13,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-gdansk.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-szczecin",
    title: "Pozycjonowanie wizytówki Google Szczecin",
    excerpt:
      "Szczecin ma rynek, którego nie ma żadne inne duże polskie miasto: realnego klienta zza zachodniej granicy. Jak przygotować profil na zapytania po niemiecku, kiedy to się opłaca i dlaczego gwiaździsty układ miasta psuje intuicję o zasięgu.",
    category: "SEO",
    date: "2026-08-26",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-szczecin.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-lublin",
    title: "Pozycjonowanie wizytówki Google Lublin",
    excerpt:
      "Lublin żyje rytmem akademickim, a to oznacza rynek, który dwa razy w roku wymienia część klientów. Jak wykorzystać wrzesień i październik, co ustawić na lipiec i sierpień oraz jak obsłużyć klienta, który szuka po ukraińsku.",
    category: "SEO",
    date: "2026-08-25",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-lublin.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-bydgoszcz",
    title: "Pozycjonowanie wizytówki Google Bydgoszcz",
    excerpt:
      "Bydgoszcz i Toruń dzieli 45 kilometrów i jedno województwo, więc firmy z obu miast regularnie wchodzą sobie w wyniki. Jak zbudować profil, który wygrywa u siebie, zanim zacznie walczyć o sąsiada, i gdzie leży granica opłacalnego zasięgu.",
    category: "SEO",
    date: "2026-08-24",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-bydgoszcz.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-bialystok",
    title: "Pozycjonowanie wizytówki Google Białystok",
    excerpt:
      "Białystok jest największym miastem w Polsce bez dużego konkurenta w promieniu stu kilometrów, a to zmienia całą matematykę lokalnego SEO. Dlaczego wejście do top 3 jest tu tańsze niż w innych miastach wojewódzkich i jak wykorzystać obsługę regionu.",
    category: "SEO",
    date: "2026-08-23",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-bialystok.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-katowice",
    title: "Pozycjonowanie wizytówki Google Katowice",
    excerpt:
      "W konurbacji górnośląskiej granice miast są dla klienta umowne, a dla Google nie. Jak wygląda Local Pack w Katowicach, gdzie kończy się realna widoczność profilu i jak ustawić obszar działania firmy pracującej w całej metropolii.",
    category: "SEO",
    date: "2026-08-22",
    readTime: 13,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-katowice.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-gdynia",
    title: "Pozycjonowanie wizytówki Google Gdynia",
    excerpt:
      "Gdyńska firma konkuruje w Mapach nie tylko z Gdynią, ale z całym Trójmiastem, bo klient wpisuje „Trójmiasto” albo nie wpisuje miasta wcale. Jak ustawić profil, żeby wygrywać u siebie i nie ginąć w zapytaniach aglomeracyjnych.",
    category: "SEO",
    date: "2026-08-21",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-gdynia.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-czestochowa",
    title: "Pozycjonowanie wizytówki Google Częstochowa",
    excerpt:
      "Częstochowa ma najbardziej skrajną sezonowość ze wszystkich dużych polskich miast, a jej szczyt przypada na sierpień. Jak przygotować profil firmy na ruch pielgrzymkowy, co zrobić z godzinami specjalnymi i jak nie zgubić klienta lokalnego przez resztę roku.",
    category: "SEO",
    date: "2026-08-20",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-czestochowa.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-radom",
    title: "Pozycjonowanie wizytówki Google Radom",
    excerpt:
      "Radom leży sto kilometrów od Warszawy i regularnie oddaje zapytania firmom, które dojeżdżają ze stolicy. Jak obronić lokalny rynek, na czym polega przewaga firmy faktycznie obecnej w mieście i które sygnały w profilu tę obecność potwierdzają.",
    category: "SEO",
    date: "2026-08-19",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-radom.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-rzeszow",
    title: "Pozycjonowanie wizytówki Google Rzeszów",
    excerpt:
      "Rzeszów rozbudowuje się szybciej, niż Mapy Google nadążają aktualizować, a nowe osiedla potrafią przez miesiące nie mieć poprawnych adresów. Co z tego wynika dla firmy, jak zgłosić brakujący adres i dlaczego to bywa najtańszy sposób na przewagę.",
    category: "SEO",
    date: "2026-08-18",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-rzeszow.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-torun",
    title: "Pozycjonowanie wizytówki Google Toruń",
    excerpt:
      "Toruńska starówka wpisana na listę UNESCO oznacza ograniczenia w ruchu, trudny dojazd i klienta, który przed wizytą sprawdza w Mapach parking. Jak ustawić atrybuty i zdjęcia, żeby odpowiedzieć na to zanim ktokolwiek zadzwoni.",
    category: "SEO",
    date: "2026-08-17",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-torun.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-sosnowiec",
    title: "Pozycjonowanie wizytówki Google Sosnowiec",
    excerpt:
      "Sosnowiec powstał ze zrośniętych osad i do dziś nie ma jednego oczywistego centrum, więc mieszkańcy szukają po nazwach dzielnic, nie po nazwie miasta. Jak zbudować profil pod Zagórze, Środulę czy Milowice i gdzie postawić pinezkę.",
    category: "SEO",
    date: "2026-08-16",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-sosnowiec.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-kielce",
    title: "Pozycjonowanie wizytówki Google Kielce",
    excerpt:
      "Kielce obsługują region, w którym nie ma drugiego dużego miasta, więc profil kielecki naturalnie ciągnie zapytania z całego województwa. Jak to wykorzystać bez rozmywania profilu i co zmienia w tym rachunku kalendarz Targów Kielce.",
    category: "SEO",
    date: "2026-08-15",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-kielce.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-gliwice",
    title: "Pozycjonowanie wizytówki Google Gliwice",
    excerpt:
      "Gliwice leżą na skrzyżowaniu A1 i A4, mają silną uczelnię techniczną i klienta, który równie często szuka usługi przy trasie, co przy domu. Jak rozdzielić te dwie intencje w profilu firmy i czym różni się tu konkurencja od reszty konurbacji.",
    category: "SEO",
    date: "2026-08-14",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-gliwice.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-bielsko-biala",
    title: "Pozycjonowanie wizytówki Google Bielsko-Biała",
    excerpt:
      "Bielsko-Biała to dwa dawne miasta po dwóch stronach Białej plus wejście w Beskidy, więc rynek zmienia się i geograficznie, i sezonowo. Jak ustawić obszar działania w stronę Szczyrku i Żywca oraz co zrobić z sezonem zimowym w profilu.",
    category: "SEO",
    date: "2026-08-13",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-bielsko-biala.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-zabrze",
    title: "Pozycjonowanie wizytówki Google Zabrze",
    excerpt:
      "Zabrze graniczy bezpośrednio z Gliwicami, Bytomiem i Rudą Śląską, a klient przekracza te granice nie zauważając ich. Jak wygląda tu realna konkurencja w Mapach, dlaczego wejście do top 3 bywa tańsze niż w Gliwicach i jak to wykorzystać.",
    category: "SEO",
    date: "2026-08-12",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-zabrze.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-bytom",
    title: "Pozycjonowanie wizytówki Google Bytom",
    excerpt:
      "Bytom od lat traci mieszkańców, a po zamkniętych firmach zostają w Mapach martwe wizytówki, które nadal zbierają wyświetlenia. Jak przejrzeć ten bałagan, zgłosić nieaktualne profile i wykorzystać sytuację, w której konkurencja tylko wygląda na obecną.",
    category: "SEO",
    date: "2026-08-11",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-bytom.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-zielona-gora",
    title: "Pozycjonowanie wizytówki Google Zielona Góra",
    excerpt:
      "Po połączeniu z gminą wiejską Zielona Góra stała się jednym z największych powierzchniowo miast w Polsce, a między dzielnicami są kilometry lasu. Co to robi z zasięgiem profilu i jak ustawić obszar działania, żeby odpowiadał rzeczywistości.",
    category: "SEO",
    date: "2026-08-10",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-zielona-gora.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-rybnik",
    title: "Pozycjonowanie wizytówki Google Rybnik",
    excerpt:
      "Rybnik to centrum plus kilkanaście dzielnic, które wyglądają i funkcjonują jak osobne miejscowości. Jak rozpisać taki rynek na frazy, dlaczego jedna pinezka nie obsłuży całego miasta i co z tego wynika dla firm z dojazdem.",
    category: "SEO",
    date: "2026-08-09",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-rybnik.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-ruda-slaska",
    title: "Pozycjonowanie wizytówki Google Ruda Śląska",
    excerpt:
      "Ruda Śląska nie ma jednego centrum ani jednego rynku, tylko kilkanaście dzielnic o własnej tożsamości i własnych nazwach w wyszukiwarce. Jak wybrać lokalizację profilu, których nazw używać w treściach i gdzie realnie kończy się widoczność.",
    category: "SEO",
    date: "2026-08-08",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-ruda-slaska.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-opole",
    title: "Pozycjonowanie wizytówki Google Opole",
    excerpt:
      "Opole jest najmniejszym miastem wojewódzkim w Polsce, więc profil z Opola naturalnie obsługuje pół województwa. Jak zbudować widoczność w regionie bez rozmycia profilu i o czym pamiętać, obsługując dwujęzyczne gminy Opolszczyzny.",
    category: "SEO",
    date: "2026-08-07",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-opole.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-tychy",
    title: "Pozycjonowanie wizytówki Google Tychy",
    excerpt:
      "Tychy zostały zaprojektowane od zera, a osiedla mają litery zamiast nazw, więc mieszkańcy szukają inaczej niż w miastach o historycznym układzie. Jak dopasować profil do tego sposobu wyszukiwania i co robić, gdy Mapy mylą adresy w osiedlach.",
    category: "SEO",
    date: "2026-08-06",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-tychy.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-dabrowa-gornicza",
    title: "Pozycjonowanie wizytówki Google Dąbrowa Górnicza",
    excerpt:
      "Dąbrowa Górnicza jest jednym z największych powierzchniowo miast w kraju, a między jej krańcami jest kilkanaście kilometrów, lasy i jeziora Pogorii. Jak wyznaczyć realny zasięg profilu w mieście, którego nie da się objąć jedną pinezką.",
    category: "SEO",
    date: "2026-08-05",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-dabrowa-gornicza.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "mobilna-wulkanizacja-jak-zwiekszyc-zasieg",
    title: "Mobilna wulkanizacja - jak zwiększyć zasięg",
    excerpt: "Cztery etapy, które w usłudze z dojazdem realnie poszerzają obszar wyświetlania: wizytówka Google wypełniona na 100% z obszarem działania zamiast adresu, strona z podstronami lokalizacyjnymi zamiast onepage'a, mapy i wzmianki na lokalnych portalach, a dopiero na końcu płatne linki. Z harmonogramem tygodniowym, przykładami i wyliczeniem, kiedy to się zwraca.",
    category: "Poradnik",
    date: "2026-09-01",
    readTime: 18,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-mobilna-wulkanizacja.svg",
    published: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-olsztyn",
    title: "Pozycjonowanie wizytówki Google Olsztyn — także metody z szarej strefy i ich cena",
    excerpt: "Co ustawić w profilu firmy z Olsztyna, żeby wejść do top 3 w Mapach. Plus uczciwy przegląd metod z szarej strefy — fraza w nazwie, całodobowe godziny, wirtualne biuro — z opisem tego, czym kończą się w praktyce i co robić zamiast nich.",
    category: "SEO",
    date: "2026-08-27",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-olsztyn.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-pila",
    title: "Pozycjonowanie wizytówki Google Piła — poradnik dla firm z Piły i powiatu",
    excerpt: "Jak firma z Piły wchodzi do top 3 w Mapach Google. Realia pilskiego rynku, mapa zasięgu do Ujścia, Kaczor, Chodzieży i Wałcza, gotowy kod Local Schema pod Piłę oraz kolejność prac na pierwszy tydzień i pierwszy miesiąc.",
    category: "SEO",
    date: "2026-08-28",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-pila.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "miauseo-opinie-skup-aut",
    title: "SEO i opinie Google - wizytówka skupu aut, 77 połączeń",
    excerpt: "Współpracę nad wizytówką Google skupu aut zaczęliśmy w czerwcu. W lipcu, pierwszym pełnym miesiącu działań, profil wygenerował 77 połączeń telefonicznych. Pokazujemy cały zakres: przygotowanie i optymalizację wizytówki, weryfikację wideo, stronę z podstronami lokalizacyjnymi wspierającą profil, zaplecze linkowe, narzędzia do zbierania opinii Google oraz walkę z zapytaniami o części samochodowe.",
    category: "Opinie",
    date: "2026-08-09",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-miauseo-opinie-skup-aut.svg",
    published: true,
  },
  {
    slug: "kiedy-nie-pozycjonowac-strony-internetowej",
    title: "Kiedy NIE pozycjonować strony? 7 sytuacji",
    excerpt: "Kiedy nie pozycjonować strony internetowej? Oto 7 sytuacji, w których SEO to zły pomysł — i co robić zamiast tego, żeby nie przepalić budżetu na start.",
    category: "Poradnik",
    date: "2026-07-18",
    readTime: 10,
    coverColor: "#f59e0b",
    coverImage: "/blog/cover-kiedy-nie-pozycjonowac-strony-internetowej.svg",
    published: true,
    popular: true,
  },
  {
    slug: "miauseo-opinie-mobilny-masaz",
    title: "MiauSEO - strona WWW i podstrony lokalizacyjne w 2026",
    excerpt: "Case study z branży masażu mobilnego. Zbudowaliśmy stronę od zera — architekturę pod frazy „mobilny masaż” i „masaż z dojazdem”, osobne podstrony lokalizacyjne dopasowane do obszarów dojazdu oraz blog budujący kontekst tematyczny wokół usługi. Opisujemy też, dlaczego projekt świadomie skupił się wyłącznie na stronie i treściach.",
    category: "Opinie",
    date: "2026-07-14",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-miauseo-opinie-mobilny-masaz.svg",
    published: true,
  },
  {
    slug: "miauseo-opinie-skup",
    title: "MiauSEO Opinie - 466 wizyt w punkcie - 3 miesiące",
    excerpt: "Skup telefonów konkurujący z sieciówkami, które mają budżety marketingowe wielokrotnie większe od całego rocznego przychodu klienta. Pokazujemy, jak rozbudowa strony pod frazę „skup telefonów”, blog, zaplecze NAP i wdrożony system opinii przełożyły się na 466 wizyt w punkcie w trzy miesiące — i dlaczego stabilność pozycji jest tu ważniejsza niż jednorazowy skok.",
    category: "Opinie",
    date: "2026-07-14",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-miauseo-opinie-skup.svg",
    published: true,
  },
  {
    slug: "miauseo-opinie-protetyk",
    title: "miauSEO - Opinie - 180 połączeń - 4 miesiące w 2026",
    excerpt: "Wpisałeś w Google „miauSEO opinie”? Zamiast obietnic pokazujemy prawdziwą współpracę z gabinetem protetycznym — od optymalizacji wizytówki Google i uporządkowania danych NAP po zmianie adresu, przez wdrożony u klienta system zbierania opinii, aż po twarde liczby: ponad 180 połączeń od kwietnia do 12 lipca 2026, ze zrzutami statystyk miesiąc po miesiącu.",
    category: "Opinie",
    date: "2026-07-12",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-miauseo-opinie-protetyk.svg",
    published: true,
    popular: true,
    caseRating: { businessName: "Gabinet protetyczny — klient MiauSEO", value: 5, count: 11 },
  },
  {
    slug: "wizytowka-google-klimatyzacja-telefony-od-klientow",
    title: "Jak wizytówka Google pomaga firmom od klimatyzacji zdobywać więcej telefonów od klientów?",
    excerpt: "W branży klimatyzacji klient nie czyta ofert — wpisuje „montaż klimatyzacji” albo „serwis klimatyzacji blisko mnie” i dzwoni do jednej z trzech pierwszych firm z Map Google. Pokazujemy, dlaczego wizytówka Google Business Profile jest dla firmy HVAC najtańszym źródłem telefonów, jak Google ustala kolejność firm i co zrobić, żeby to Twój numer był na górze.",
    category: "SEO",
    date: "2026-07-07",
    readTime: 19,
    coverColor: "#0ea5e9",
    coverImage: "/blog/cover-klimatyzacja-wizytowka.svg",
    published: true,
    popular: true,
  },
  {
    slug: "reklama-pomocy-drogowej-skuteczne-metody",
    title: "Reklama pomocy drogowej – skuteczne sposoby na zdobywanie klientów",
    excerpt: "W pomocy drogowej wygrywa ten, kto pierwszy odbierze telefon od kierowcy na poboczu. Pokazujemy, które kanały realnie generują zlecenia — Google Ads, SEO lokalne, wizytówka Google, współprace z warsztatami — ile to kosztuje i jak ułożyć z tego plan działania na pierwsze 30 dni.",
    category: "Poradnik",
    date: "2026-06-17",
    readTime: 14,
    coverColor: "#f59e0b",
    coverImage: "/blog/cover-reklama-pomoc-drogowa.svg",
    published: true,
  },
  {
    slug: "google-ads-pomoc-drogowa",
    title: "Google Ads dla pomocy drogowej – kampania, która dzwoni telefon 24/7",
    excerpt: "Google Ads to dla pomocy drogowej kanał numer jeden — łapie klienta dokładnie w sekundzie, w której wpisuje „laweta”. Rozkładamy na czynniki pierwsze kampanię call-only, targetowanie geograficzne, harmonogram stawek dobowych i listę słów kluczowych, która nie przepala budżetu.",
    category: "Poradnik",
    date: "2026-06-16",
    readTime: 13,
    coverColor: "#1d4ed8",
    coverImage: "/blog/cover-google-ads-pomoc-drogowa.svg",
    published: true,
  },
  {
    slug: "seo-lokalne-dla-firm",
    title: "SEO lokalne dla firm – jak trafić do top 3 Google Maps i zdobywać klientów z okolicy",
    excerpt: "SEO lokalne decyduje o tym, czy lokalna firma pojawi się w „local packu” nad wynikami, czy zniknie poniżej konkurencji. Przewodnik po wizytówce Google, spójności NAP, słowach kluczowych, opiniach i podstronach lokalizacyjnych — z planem wdrożenia krok po kroku.",
    category: "SEO",
    date: "2026-06-15",
    readTime: 14,
    coverColor: "#0d9488",
    coverImage: "/blog/cover-seo-lokalne-dla-firm.svg",
    published: true,
  },
  {
    slug: "reklama-firm-uslugowych",
    title: "Reklama firm usługowych – jak pozyskiwać klientów lokalnie w 2026 roku",
    excerpt: "Hydraulik, elektryk, sprzątanie, pomoc drogowa — firmy usługowe łączy ta sama logika: klient szuka lokalnie i w momencie potrzeby. Pokazujemy uniwersalny system reklamy, który łapie klienta w intencji i buduje powtarzalne zlecenia, oraz plan na pierwsze 30 dni.",
    category: "Poradnik",
    date: "2026-06-14",
    readTime: 13,
    coverColor: "#7c3aed",
    coverImage: "/blog/cover-reklama-firm-uslugowych.svg",
    published: true,
  },
  {
    slug: "masaz-z-dojazdem-poznan-case-study",
    title: "Masaż z dojazdem Poznań — top 3 Google Maps w branży z 50 konkurentami w 60 dni",
    excerpt: "Branża masażu mobilnego w Poznaniu to ponad 50 aktywnych profili GBP walczących o te same frazy. Klientka zaczynała bez jednej opinii i z wizytówką sprzed 3 lat. Oto co zrobiliśmy przez pierwsze 60 dni i jak skończyła w top 3 na najważniejszej frazie.",
    category: "Poradnik",
    date: "2026-06-09",
    readTime: 7,
    coverColor: "#0d9488",
    coverImage: "/blog/cover-ref-masaz.svg",
    published: true,
    hideFromBlog: true,
  },
  {
    slug: "protetyk-pila-case-study",
    title: "Protetyk Piła — jak dotrzeć do seniorów przez Google i zapełnić grafik na 3 tygodnie do przodu",
    excerpt: "Gabinet protetyczny w Pile miał świetną opinię wśród stałych pacjentów i zerową widoczność w Google. Problemem nie był brak jakości — był brak obecności tam, gdzie seniorzy szukają dziś lekarzy. Pokazujemy jak to zmieniliśmy.",
    category: "Poradnik",
    date: "2026-06-09",
    readTime: 6,
    coverColor: "#7c3aed",
    coverImage: "/blog/cover-ref-protetyk.svg",
    published: true,
    hideFromBlog: true,
  },
  {
    slug: "serwis-telefonow-poznan-case-study",
    title: "Serwis telefonów Poznań — 154 wizyty z wizytówki Google w pierwszym miesiącu współpracy",
    excerpt: "Lokalny serwis telefonów w Poznaniu konkurował z sieciowymi serwisami i kilkudziesięcioma innymi punktami. Po 30 dniach optymalizacji wizytówki Google — 154 wizyty i wzrost o 26,2% rok do roku. Rozkładamy to na czynniki pierwsze.",
    category: "Poradnik",
    date: "2026-06-09",
    readTime: 6,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-ref-serwis.svg",
    published: true,
    hideFromBlog: true,
  },
  {
    slug: "najwieksze-bledy-pozycjonowanie-wizytowki-google-2026",
    title: "Największe błędy w pozycjonowaniu wizytówki Google w 2026 — dlaczego firmy tracą lokalnych klientów",
    excerpt: "Większość wizytówek nie przegrywa przez puste pola, tylko przez błędy, których nie widać w panelu: rozjechane encje, niespójny NAP, kanibalizację lokalizacji, złe kategorie i brak strategii pod AI Overviews. Analizujemy 10 zaawansowanych błędów lokalnego SEO — z tabelą ryzyka i trzema case studies z audytów.",
    category: "SEO",
    date: "2026-06-11",
    readTime: 18,
    coverColor: "#b91c1c",
    coverImage: "/blog/cover-bledy-wizytowka-2026.svg",
    published: true,
    popular: true,
  },
  {
    slug: "jak-polaczyc-claude-code-z-wordpressem",
    title: "Jak połączyć Claude Code z WordPressem? Kompletny przewodnik po integracji i automatyzacjach",
    excerpt: "Claude Code (często wyszukiwany jako „Cloud Code”) potrafi zarządzać stroną WordPress jak doświadczony developer — publikować wpisy, optymalizować SEO, pisać wtyczki i utrzymywać serwer. Pokazujemy 5 metod integracji, 10 praktycznych zastosowań, koszty wdrożenia i zasady bezpieczeństwa.",
    category: "Sztuczna Inteligencja",
    date: "2026-06-11",
    readTime: 21,
    coverColor: "#21759b",
    coverImage: "/blog/cover-claude-code-wordpress.svg",
    published: true,
  },
  {
    slug: "claude-code-skills-jak-dzialaja",
    title: "Claude Code Skills — czym są, jak działają i jak napisać własny skill od zera",
    excerpt: "Skills to jeden z najmocniejszych, a zarazem najmniej znanych mechanizmów Claude Code. Pozwalają zapisać cały workflow — od uruchamiania aplikacji po review kodu — jako komendę slash i odtwarzać go jednym wpisem. Kompletny przewodnik dla programistów i agencji.",
    category: "Sztuczna Inteligencja",
    date: "2026-06-08",
    readTime: 12,
    coverColor: "#0ea5e9",
    coverImage: "/blog/cover-claude-code-skills.svg",
    published: true,
  },
  {
    slug: "jak-podpiac-domene-vercel-claude-code",
    title: "Jak podpiąć domenę pod stronę z Claude Code — Vercel, GitHub i darmowa baza danych krok po kroku",
    excerpt: "Zrobiłeś stronę w Claude Code i chcesz ją opublikować pod własną domeną? Ten przewodnik przeprowadzi Cię przez cały proces — od pierwszego commita na GitHub, przez deploy na Vercel, po konfigurację DNS i darmową bazę danych. Zero wiedzy technicznej wymagane.",
    category: "Sztuczna Inteligencja",
    date: "2026-06-09",
    readTime: 14,
    coverColor: "#0f172a",
    coverImage: "/blog/cover-vercel-claude-code.svg",
    published: true,
  },
  {
    slug: "claude-fable-5-mythos-5-anthropic",
    title: "Claude Fable 5 i Mythos 5 — Anthropic wypuścił najmocniejszy model w historii",
    excerpt: "Anthropic ogłosił Claude Fable 5 — pierwszy model klasy Mythos dostępny publicznie. Stripe skompresował nim miesiące pracy inżynierskiej do dni. Model pobił Pokémon FireRed używając wyłącznie surowych zrzutów ekranu. Oto co to oznacza w praktyce.",
    category: "Sztuczna Inteligencja",
    date: "2026-06-09",
    readTime: 10,
    coverColor: "#7c3aed",
    coverImage: "/blog/cover-claude-fable-5.svg",
    published: true,
  },
  {
    slug: "google-search-console-raporty-ai-2026",
    title: "Nowe raporty AI w Google Search Console — co mierzą i co to zmienia",
    excerpt: "Google właśnie uruchomił dedykowane raporty widoczności w AI Overviews i AI Mode. Po raz pierwszy możesz zobaczyć, które strony trafiają do odpowiedzi generatywnych — ale bez danych o kliknięciach. Co to oznacza dla Twojej strategii SEO?",
    category: "SEO",
    date: "2026-06-03",
    readTime: 5,
    coverColor: "#4285F4",
    coverImage: "/blog/cover-search-console-ai.svg",
    published: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google",
    title: "Pozycjonowanie wizytówki Google – kompletny przewodnik 2026",
    excerpt: "Czym jest pozycjonowanie wizytówki Google, jak działa algorytm Local Pack i co zrobić, żeby Twoja firma znalazła się w top 3 Google Maps? Praktyczny przewodnik eksperta – bez lania wody.",
    category: "SEO",
    date: "2026-05-30",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-pozycjonowanie-wizytowki.svg",
    published: true,
    popular: true,
  },
  {
    slug: "czynniki-rankingowe-wizytowki-google-2026",
    title: "Czynniki rankingowe wizytówki Google w 2026 — pełna lista z oceną ważności",
    excerpt: "34 czynniki rankingowe Google Business Profile sklasyfikowane od A (krytyczne) do E (marginalne). Kompletna tabela z opisem każdego sygnału i wskazówkami wdrożeniowymi.",
    category: "SEO",
    date: "2026-05-27",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-czynniki-rankingowe.svg",
    published: true,
  },
  {
    slug: "jak-dobierac-slowa-kluczowe-do-pozycjonowania",
    title: "Jak dobierać słowa kluczowe do pozycjonowania — kompletny przewodnik",
    excerpt: "Dobór słów kluczowych to fundament każdej strategii SEO. Jak analizować intencję wyszukiwania, korzystać z narzędzi i budować listę fraz, które realnie przyciągają klientów — nie tylko ruch.",
    category: "SEO",
    date: "2026-05-27",
    readTime: 12,
    coverColor: "#059669",
    coverImage: "/blog/cover-slowa-kluczowe.svg",
    published: true,
  },
  {
    slug: "jak-dodac-local-schema-do-strony",
    title: "Jak dodać local schema markup do swojej strony — kompletny przewodnik",
    excerpt: "Schema markup LocalBusiness to jeden z najskuteczniejszych sygnałów lokalnego SEO, który większość firm ignoruje. Pokażemy Ci jak go poprawnie wdrożyć w każdym środowisku — z gotowym kodem JSON-LD.",
    category: "SEO",
    date: "2026-05-27",
    readTime: 10,
    coverColor: "#6366f1",
    coverImage: "/blog/cover-local-schema.svg",
    published: true,
  },
  {
    slug: "jak-odzyskac-dostep-do-wizytowki-google",
    title: "Jak odzyskać dostęp do wizytówki Google? Krok po kroku",
    excerpt: "Zgubiłeś dostęp do profilu Google Business? Pracownik odszedł z kluczami do konta? Firma zmieniła właściciela? Jest kilka sposobów na odzyskanie kontroli — bez płacenia komukolwiek.",
    category: "Poradnik",
    date: "2026-05-15",
    readTime: 6,
    coverColor: "#3b82f6",
    coverImage: "/blog/cover-odzyskaj.svg",
    published: true,
  },
  {
    slug: "jak-usunac-negatywne-opinie-z-google",
    title: "Jak usunąć negatywne opinie z Google? Co możesz, a czego nie",
    excerpt: "Nie możesz usunąć każdej złej recenzji — ale część możesz zgłosić i usunąć legalnie. Dowiedz się, które opinie naruszają zasady Google i jak skutecznie je zgłosić.",
    category: "Opinie",
    date: "2026-04-28",
    readTime: 6,
    coverColor: "#dc2626",
    coverImage: "/blog/cover-usun-opinie.svg",
    published: true,
  },
  {
    slug: "negatywna-opinia-google-co-zrobic",
    title: "Dostałem negatywną opinię na wizytówce Google – co teraz?",
    excerpt: "Negatywna recenzja to nie wyrok. Jak na nią reagujesz publicznie, mówi klientom więcej o Twojej firmie niż sama treść opinii. Oto plan działania krok po kroku.",
    category: "Opinie",
    date: "2026-04-14",
    readTime: 5,
    coverColor: "#f97316",
    coverImage: "/blog/cover-negatywna-opinia.svg",
    published: true,
  },
  {
    slug: "czy-wizytowka-google-jest-platna",
    title: "Czy wizytówka Google jest płatna? Porównanie z Facebook i reklamami",
    excerpt: "Google Business Profile jest w 100% bezpłatny i takim pozostanie. Ale jak wypada w porównaniu z płatnym zasięgiem na Facebooku czy Google Ads? Zrobimy to uczciwie.",
    category: "Poradnik",
    date: "2026-03-30",
    readTime: 5,
    coverColor: "#10b981",
    coverImage: "/blog/cover-platna.svg",
    published: true,
  },
  {
    slug: "linki-do-wizytowki-google",
    title: "Gdzie pozyskiwać linki do wizytówki Google i po co to robić?",
    excerpt: "Linki prowadzące do profilu GBP wzmacniają sygnały widoczności w wynikach lokalnych. Oto 8 miejsc, gdzie warto je umieszczać — i dlaczego to nic nie kosztuje.",
    category: "SEO",
    date: "2026-02-24",
    readTime: 5,
    coverColor: "#0284c7",
    coverImage: "/blog/cover-linki.svg",
    published: true,
  },
  {
    slug: "ile-kosztuje-pozycjonowanie-strony-internetowej",
    title: "Ile kosztuje pozycjonowanie strony internetowej w 2026 roku?",
    excerpt: "Od 500 do 20 000 zł miesięcznie — i obie kwoty mogą być uczciwe. Dowiedz się, za co płacisz, czego unikać i jak wyliczyć ROI z SEO zanim podpiszesz umowę.",
    category: "Poradnik",
    date: "2026-02-10",
    readTime: 7,
    coverColor: "#059669",
    coverImage: "/blog/cover-koszt-seo.svg",
    published: true,
    popular: true,
  },
  {
    slug: "reklama-kancelarii-adwokackiej-google",
    title: "Reklama kancelarii adwokackiej w Google – co wolno, co działa",
    excerpt: "Adwokaci i radcowie mogą reklamować się w Google, ale obowiązują ich zasady etyki zawodowej. Sprawdź, jak prowadzić skuteczny marketing prawniczy w granicach przepisów.",
    category: "Poradnik",
    date: "2026-01-28",
    readTime: 7,
    coverColor: "#1e40af",
    coverImage: "/blog/cover-kancelaria.svg",
    published: true,
  },
  {
    slug: "jak-promowac-warsztat-samochodowy-google",
    title: "Jak promować warsztat samochodowy w Google? Wizytówka i reklamy",
    excerpt: "Warsztat samochodowy to jedna z branż, gdzie klient szuka w ostatniej chwili i lokalnie. Google Business Profile i Google Ads to Twoje najważniejsze narzędzia.",
    category: "SEO",
    date: "2026-01-14",
    readTime: 6,
    coverColor: "#b45309",
    coverImage: "/blog/cover-warsztat.svg",
    published: true,
  },
  {
    slug: "salon-kosmetyczny-facebook-ads",
    title: "Salon kosmetyczny i Facebook Ads – jak zarabiać na reklamach Meta?",
    excerpt: "Salon piękności to idealne miejsce dla reklam na Facebooku i Instagramie. Zdjęcia przed/po, targetowanie kobiet z okolicy, retargeting — oto konkretna strategia.",
    category: "Poradnik",
    date: "2025-12-20",
    readTime: 7,
    coverColor: "#db2777",
    coverImage: "/blog/cover-salon.svg",
    published: true,
  },
  {
    slug: "opinie-google-jak-zdobywac-skutecznie",
    title: "Opinie w Google – jak zbierać je bez nachalnego proszenia?",
    excerpt: "Klienci rzadko wystawiają opinie z własnej inicjatywy. Poznaj sprawdzone metody, które zwiększają liczbę recenzji bez spamowania.",
    category: "Opinie",
    date: "2025-04-22",
    readTime: 5,
    coverColor: "#16a34a",
    coverImage: "/blog/cover-opinie.svg",
    published: true,
  },
  {
    slug: "zdjecia-w-wizytowce-google-ktore-dzialaja",
    title: "Zdjęcia w wizytówce Google – które naprawdę wpływają na pozycję?",
    excerpt: "Nie każde zdjęcie pomaga. Sprawdź, jakie formaty, rozmiary i treści Google premiuje — i których unikać, żeby nie zaszkodzić profilowi.",
    category: "Wizytówka",
    date: "2025-03-05",
    readTime: 5,
    coverColor: "#0ea5e9",
    coverImage: "/blog/cover-zdjecia.svg",
    published: true,
  },
  {
    slug: "nap-wizytowka-google-co-to-jest",
    title: "NAP w wizytówce Google – czym jest i jak poprawnie ją skonfigurować?",
    excerpt: "Nazwa, adres, telefon — trzy dane, które muszą być identyczne w każdym miejscu w sieci. Dowiedz się, czym jest NAP, dlaczego to fundament local SEO i jak przeprowadzić audyt spójności.",
    category: "SEO",
    date: "2026-05-08",
    readTime: 6,
    coverColor: "#6366f1",
    coverImage: "/blog/cover-nap.svg",
    published: true,
  },
  {
    slug: "wizytowka-google-popularne-oszustwa",
    title: "Wizytówka Google – najpopularniejsze oszustwa, na które uważaj",
    excerpt: "Od fałszywych faktur za 'odnowienie' po kupowanie recenzji — oszustwa związane z Google Business Profile psują rynek i mogą skończyć się zawieszeniem profilu.",
    category: "Poradnik",
    date: "2026-04-20",
    readTime: 7,
    coverColor: "#ef4444",
    coverImage: "/blog/cover-oszustwa.svg",
    published: true,
  },
  {
    slug: "siedziba-mala-miejscowosc-local-seo",
    title: "Siedziba w małej miejscowości – jak zdobyć klientów z dużego miasta?",
    excerpt: "Firma zarejestrowana w małej wsi, ale klientów szukasz w pobliskim mieście? Strategia NAP, podstrony lokalizacyjne i area service to Twoje główne narzędzia.",
    category: "SEO",
    date: "2026-04-05",
    readTime: 8,
    coverColor: "#14b8a6",
    coverImage: "/blog/cover-miejscowosc.svg",
    published: true,
  },
  {
    slug: "opis-firmy-google-business-profile-jak-napisac",
    title: "Opis firmy w Google Business Profile – jak napisać go skutecznie?",
    excerpt: "750 znaków, które muszą przekonać i klienta, i algorytm. Pokazujemy strukturę opisu, który działa — z przykładami dla różnych branż.",
    category: "Wizytówka",
    date: "2025-02-18",
    readTime: 6,
    coverColor: "#ec4899",
    coverImage: "/blog/cover-opis.svg",
    published: true,
  },

  // Wizytówka posts
  {
    slug: "kategorie-wizytowka-google",
    title: "Kategorie w wizytówce Google – jak wybrać właściwe i dlaczego to kluczowe?",
    excerpt: "Wybór kategorii to jedna z najważniejszych decyzji przy tworzeniu wizytówki Google. Zła kategoria główna może kosztować Cię pierwszą stronę wyników nawet jeśli wszystko inne jest idealne. Kompletny przewodnik z listą kategorii i strategią doboru.",
    category: "Wizytówka",
    date: "2026-05-26",
    readTime: 8,
    coverColor: "#0284c7",
    coverImage: "/blog/cover-wiz-kategorie.svg",
    published: true,
  },
  {
    slug: "godziny-otwarcia-wizytowka-google",
    title: "Godziny otwarcia w wizytówce Google – jak ustawić poprawnie i nie stracić klientów",
    excerpt: "Nieaktualne godziny otwarcia to jeden z najczęstszych powodów negatywnych opinii. Google weryfikuje zgodność podanych godzin z rzeczywistością. Dowiedz się jak ustawić godziny regularne, świąteczne i specjalne — i dlaczego to ważne dla rankingu.",
    category: "Wizytówka",
    date: "2026-05-24",
    readTime: 6,
    coverColor: "#0369a1",
    coverImage: "/blog/cover-wiz-godziny.svg",
    published: true,
  },
  {
    slug: "atrybuty-wizytowka-google",
    title: "Atrybuty wizytówki Google – czym są i jak wypełnić je skutecznie?",
    excerpt: "Atrybuty to niedoceniany element GBP, który pozwala wyróżnić Twoją firmę w wynikach lokalnych. Bezgotówkowe płatności, dostęp dla wózków, WiFi, obsługa w języku angielskim — każdy atrybut może być powodem do wyboru Ciebie zamiast konkurencji.",
    category: "Wizytówka",
    date: "2026-05-22",
    readTime: 6,
    coverColor: "#0891b2",
    coverImage: "/blog/cover-wiz-atrybuty.svg",
    published: true,
  },
  {
    slug: "uslugi-wizytowka-google-business",
    title: "Usługi w wizytówce Google Business Profile – jak dodać i opisać żeby sprzedawały?",
    excerpt: "Sekcja Usługi w GBP to bezpłatne miejsce na zaprezentowanie oferty bezpośrednio w wynikach Google — przed wejściem na stronę. Większość firm zostawia ją pustą lub wypełnia byle jak. Oto jak zrobić to skutecznie.",
    category: "Wizytówka",
    date: "2026-05-20",
    readTime: 7,
    coverColor: "#0e7490",
    coverImage: "/blog/cover-wiz-uslugi.svg",
    published: true,
  },
  {
    slug: "posty-wizytowka-google",
    title: "Google Posts – jak tworzyć posty w wizytówce, które przyciągają klientów?",
    excerpt: "Google Posts to funkcja, którą większość firm ignoruje, a która pozwala publikować aktualności, oferty, wydarzenia i produkty bezpośrednio w wynikach wyszukiwania. Dowiedz się jak je tworzyć, jak często i co pisać żeby działały.",
    category: "Wizytówka",
    date: "2026-05-18",
    readTime: 7,
    coverColor: "#0284c7",
    coverImage: "/blog/cover-wiz-posty.svg",
    published: true,
  },
  {
    slug: "pytania-odpowiedzi-wizytowka-google",
    title: "Sekcja Q&A w wizytówce Google – jak zarządzać pytaniami i odpowiedziami?",
    excerpt: "Sekcja pytań i odpowiedzi w GBP jest publiczna — każdy może zadać pytanie i każdy może odpowiedzieć. W tym Twoja konkurencja. Naucz się jak monitorować Q&A, odpowiadać na pytania i samodzielnie zadawać pytania, żeby kontrolować narrację.",
    category: "Wizytówka",
    date: "2026-05-16",
    readTime: 6,
    coverColor: "#0369a1",
    coverImage: "/blog/cover-wiz-qa.svg",
    published: true,
  },
  {
    slug: "produkty-wizytowka-google-business",
    title: "Produkty w wizytówce Google Business Profile – kiedy i jak je dodać?",
    excerpt: "Katalog produktów w GBP pozwala pokazać co sprzedajesz bezpośrednio w wizytówce — ze zdjęciami, opisami i cenami. Dla sklepów, salonów i firm e-commerce to funkcja, której nie można pominąć. Dowiedz się kiedy warto użyć produktów zamiast usług.",
    category: "Wizytówka",
    date: "2026-05-14",
    readTime: 6,
    coverColor: "#0284c7",
    coverImage: "/blog/cover-wiz-produkty.svg",
    published: true,
  },
  {
    slug: "weryfikacja-wizytowki-google",
    title: "Weryfikacja wizytówki Google – wszystkie metody krok po kroku (2026)",
    excerpt: "Bez weryfikacji wizytówka Google jest niewidoczna w wynikach lokalnych. Google oferuje kilka metod weryfikacji — pocztówką, telefonicznie, przez e-mail, wideo lub natychmiastowo. Sprawdź która metoda jest dostępna dla Twojej firmy i jak przejść przez cały proces.",
    category: "Wizytówka",
    date: "2026-05-12",
    readTime: 8,
    coverColor: "#155e75",
    coverImage: "/blog/cover-wiz-weryfikacja.svg",
    published: true,
  },
  {
    slug: "sekcja-informacje-wizytowka-google",
    title: "Sekcja Informacje w wizytówce Google – kompletny przewodnik po wszystkich polach",
    excerpt: "Wizytówka Google ma dziesiątki pól do wypełnienia, które większość firm ignoruje. Każde z nich może wpłynąć na to, czy klient Cię znajdzie i czy Ci zaufa. Przejdziemy przez wszystkie pola sekcji Informacje — co wpisać, czego unikać i co ma wpływ na ranking.",
    category: "Wizytówka",
    date: "2026-05-10",
    readTime: 9,
    coverColor: "#0284c7",
    coverImage: "/blog/cover-wiz-informacje.svg",
    published: true,
  },
  {
    slug: "wiele-lokalizacji-google-business-profile",
    title: "Wiele lokalizacji w Google Business Profile – jak zarządzać wieloma wizytówkami?",
    excerpt: "Prowadzisz firmę z kilkoma oddziałami, salonami lub punktami sprzedaży? Zarządzanie wieloma wizytówkami GBP ma swoje reguły — od grupowania kont przez bulk verification po spójność NAP. Dowiedz się jak to zorganizować żeby żadna lokalizacja nie gryzła pozostałych.",
    category: "Wizytówka",
    date: "2026-05-08",
    readTime: 8,
    coverColor: "#0369a1",
    coverImage: "/blog/cover-wiz-lokalizacje.svg",
    published: true,
  },

  {
    slug: "jak-sprawdzic-reklamy-konkurencji-na-facebooku",
    title: "Jak sprawdzić reklamy konkurencji na Facebooku – kompletny przewodnik",
    excerpt: "Chcesz wiedzieć, co reklamuje Twoja konkurencja na Facebooku i Instagramie? Meta Ad Library to darmowe narzędzie, które pokazuje wszystkie aktywne reklamy dowolnej firmy. Sprawdź jak z niego korzystać, co analizować i jak wyciągnąć z tego realną przewagę.",
    category: "Poradnik",
    date: "2026-06-03",
    readTime: 9,
    coverColor: "#1e40af",
    coverImage: "/blog/cover-reklamy-fb-konkurencja.svg",
    published: true,
  },
  {
    slug: "jak-nadac-prawa-menedzerskie-wizytowka-google",
    title: "Jak nadać prawa menedżerskie do wizytówki Google – krok po kroku",
    excerpt: "Chcesz dać agencji lub pracownikowi dostęp do wizytówki Google bez oddawania kontroli nad kontem? Prawa menedżerskie w GBP to właściwe rozwiązanie. Pokazujemy jak je nadać, jakie są różnice między właścicielem a menedżerem i jak bezpiecznie zarządzać dostępami.",
    category: "Poradnik",
    date: "2026-06-02",
    readTime: 8,
    coverColor: "#0284c7",
    coverImage: "/blog/cover-menedzer.svg",
    published: true,
  },
  {
    slug: "pozycjonowanie-hoteli-w-mapach-google",
    title: "Pozycjonowanie hoteli w Mapach Google – przewodnik 2026",
    excerpt: "Jak sprawić, żeby hotel, pensjonat lub obiekt noclegowy pojawiał się w top 3 Google Maps? Omawiam 3 czynniki rankingowe, optymalizację profilu GBP dla HoReCa, zarządzanie opiniami i najczęstsze błędy, które kosztują rezerwacje.",
    category: "SEO",
    date: "2026-06-02",
    readTime: 13,
    coverColor: "#7c3aed",
    coverImage: "/blog/cover-hotel.svg",
    published: true,
  },

  // WordPress posts
  {
    slug: "zawirusowana-strona-wordpress-co-zrobic",
    title: "Zawirusowana strona na WordPressie – co zrobić krok po kroku",
    excerpt: "Przekierowania na podejrzane strony, obcy kod w plikach, spam w Google Search Console — objawy włamania są różne. Oto plan działania, który pozwoli Ci odzyskać stronę bez płacenia okupu.",
    category: "WordPress",
    date: "2026-05-20",
    readTime: 9,
    coverColor: "#dc2626",
    coverImage: "/blog/cover-wp-wirusy.svg",
    published: true,
  },
  {
    slug: "bialy-ekran-wordpress-jak-naprawic",
    title: "Biały ekran WordPress (White Screen of Death) – jak naprawić?",
    excerpt: "Wchodzisz na stronę i widzisz tylko biel. Żadnego błędu, żadnego komunikatu. To klasyczny White Screen of Death w WordPress. Poznaj 6 przyczyn i sprawdzonych sposobów naprawy bez utraty danych.",
    category: "WordPress",
    date: "2026-05-18",
    readTime: 7,
    coverColor: "#334155",
    coverImage: "/blog/cover-wp-bialy-ekran.svg",
    published: true,
  },
  {
    slug: "nie-moge-zalogowac-sie-do-wordpressa",
    title: "Nie mogę się zalogować do WordPressa – jak odzyskać dostęp?",
    excerpt: "Zapomniane hasło, zablokowane konto po ataku brute-force, utracony dostęp do e-maila — to trzy różne problemy wymagające różnych rozwiązań. Pokażemy każde z nich, łącznie z naprawą przez phpMyAdmin.",
    category: "WordPress",
    date: "2026-05-15",
    readTime: 6,
    coverColor: "#7c3aed",
    coverImage: "/blog/cover-wp-logowanie.svg",
    published: true,
  },
  {
    slug: "wordpress-blad-500-internal-server-error",
    title: "WordPress błąd 500 (Internal Server Error) – przyczyny i naprawa",
    excerpt: "HTTP 500 to jeden z najbardziej frustrujących błędów, bo nie mówi Ci nic konkretnego. Za każdym razem problem leży gdzie indziej — w .htaccess, wtyczce, motywie albo limitach PHP. Sprawdź wszystkie po kolei.",
    category: "WordPress",
    date: "2026-05-12",
    readTime: 8,
    coverColor: "#ea580c",
    coverImage: "/blog/cover-wp-blad-500.svg",
    published: true,
  },
  {
    slug: "wordpress-dziala-wolno-jak-przyspieszyc",
    title: "WordPress działa wolno – jak przyspieszyć stronę w 2026?",
    excerpt: "Strona ładuje się 8 sekund? Każda sekunda opóźnienia kosztuje Cię klientów i pozycje w Google. Oto konkretna lista optymalizacji — od cache przez obrazki aż po wybór hostingu — uszeregowana od najważniejszych.",
    category: "WordPress",
    date: "2026-05-08",
    readTime: 10,
    coverColor: "#0d9488",
    coverImage: "/blog/cover-wp-wolna-strona.svg",
    published: true,
  },
  {
    slug: "aktualizacja-wordpress-zepsuta-strone-co-zrobic",
    title: "Aktualizacja WordPressa zepsuła stronę – co zrobić?",
    excerpt: "Kliknąłeś 'Aktualizuj wszystko' i strona przestała działać. Klasyczny scenariusz. Dowiedz się, jak bezpiecznie przywrócić poprzednią wersję, którą wtyczkę lub motyw wyłączyć jako pierwszą i jak uniknąć tego problemu w przyszłości.",
    category: "WordPress",
    date: "2026-05-05",
    readTime: 7,
    coverColor: "#d97706",
    coverImage: "/blog/cover-wp-aktualizacja.svg",
    published: true,
  },
  {
    slug: "formularz-kontaktowy-wordpress-nie-wysyla-maili",
    title: "Formularz kontaktowy WordPress nie wysyła maili – rozwiązanie",
    excerpt: "Contact Form 7, WPForms, Gravity Forms — każdy z nich może przestać wysyłać wiadomości, jeśli hosting blokuje funkcję mail(). Sprawdź, dlaczego formularze milczą i jak to naprawić w 15 minut za pomocą SMTP.",
    category: "WordPress",
    date: "2026-04-28",
    readTime: 6,
    coverColor: "#059669",
    coverImage: "/blog/cover-wp-formularz.svg",
    published: true,
  },
  {
    slug: "wordpress-this-site-is-experiencing-technical-difficulties",
    title: "WordPress: 'This site is experiencing technical difficulties' – co to znaczy?",
    excerpt: "Ten komunikat pojawia się od WordPress 5.2 i zastępuje stary White Screen of Death. Brzmi groźnie, ale zazwyczaj oznacza konkretny błąd PHP w wtyczce lub motywie. Oto jak to zdiagnozować bez dostępu do panelu.",
    category: "WordPress",
    date: "2026-04-22",
    readTime: 5,
    coverColor: "#475569",
    coverImage: "/blog/cover-wp-blad-techniczny.svg",
    published: true,
  },
  {
    slug: "wordpress-nie-wyswietla-sie-po-migracji-hosting",
    title: "Strona WordPress nie wyświetla się po migracji na nowy hosting – rozwiązanie",
    excerpt: "Przeniosłeś stronę, ale widzisz błąd 500, białą stronę albo stary adres nadal się wyświetla. Migracja WordPressa to pułapka, jeśli zapomnisz o bazie danych, adresie URL lub propagacji DNS. Rozwiążemy każdy przypadek.",
    category: "WordPress",
    date: "2026-04-15",
    readTime: 8,
    coverColor: "#0284c7",
    coverImage: "/blog/cover-wp-migracja.svg",
    published: true,
  },
  {
    slug: "konflikt-wtyczek-wordpress-jak-zdiagnozowac",
    title: "Konflikt wtyczek WordPress – jak zdiagnozować i naprawić?",
    excerpt: "Zainstalowałeś nową wtyczkę i coś przestało działać, ale nie wiesz co. Albo masz 40 wtyczek i strona się sypie. Pokażemy metodę bisekcji do szybkiej diagnozy konfliktu bez zgadywania.",
    category: "WordPress",
    date: "2026-04-08",
    readTime: 6,
    coverColor: "#4f46e5",
    coverImage: "/blog/cover-wp-wtyczki.svg",
    published: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-konin",
    title: "Pozycjonowanie wizytówki Google Konin",
    excerpt:
      "Konin rozcina Warta, a Stare Miasto i Nowy Konin to w Mapach dwa osobne rynki. Pokazujemy, jak zmierzyć widoczność profilu firmy siatką punktów, zanim wydasz złotówkę na zmiany, i co z takiego pomiaru realnie wynika.",
    category: "SEO",
    date: "2026-08-01",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-konin.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-inowroclaw",
    title: "Pozycjonowanie wizytówki Google Inowrocław",
    excerpt:
      "Inowrocław ma 2204 osoby na kilometr kwadratowy i wyraźny rytm sezonu uzdrowiskowego. Jak ustawić godziny, posty i zdjęcia tak, żeby profil firmy nadążał za zmianą zapytań w ciągu roku, zamiast stać w miejscu od stycznia do grudnia.",
    category: "SEO",
    date: "2026-08-02",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-inowroclaw.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-stargard",
    title: "Pozycjonowanie wizytówki Google Stargard",
    excerpt:
      "Stargard leży za blisko Szczecina, żeby to ignorować. Szczecińskie firmy zbierają stargardzkie zapytania, a lokalna firma stoi niżej we własnym mieście. Trzy przewagi, które ma tylko firma ze Stargardu, i jak je wprowadzić do profilu.",
    category: "SEO",
    date: "2026-08-03",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-stargard.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-piotrkow-trybunalski",
    title: "Pozycjonowanie wizytówki Google Piotrków Trybunalski",
    excerpt:
      "W Piotrkowie dużo firm pracuje z dojazdem, a profil bez adresu rządzi się innymi prawami niż profil z lokalem. Czym różnią się te dwa typy, gdzie naprawdę leży pinezka firmy mobilnej i dlaczego adres wirtualny jest tu najdroższym skrótem.",
    category: "SEO",
    date: "2026-08-04",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-piotrkow-trybunalski.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-siedlce",
    title: "Pozycjonowanie wizytówki Google Siedlce",
    excerpt:
      "Siedlce to 2356 osób na kilometr kwadratowy i gęsty rynek usługowy. Kategoria główna decyduje, na jakie zapytania w ogóle startujesz, a sekcja usług tę pulę poszerza za darmo. Pokazujemy trik na sprawdzenie kategorii konkurencji.",
    category: "SEO",
    date: "2026-08-05",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-siedlce.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-suwalki",
    title: "Pozycjonowanie wizytówki Google Suwałki",
    excerpt:
      "Suwałki mają 68 tysięcy mieszkańców i najbliższe większe miasto daleko. W takim regionie odległość działa inaczej: profil firmy nie dowiezie klienta z drugiego końca powiatu, ale strona z podstronami lokalizacyjnymi już tak.",
    category: "SEO",
    date: "2026-08-06",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-suwalki.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-ostrowiec-swietokrzyski",
    title: "Pozycjonowanie wizytówki Google Ostrowiec Świętokrzyski",
    excerpt:
      "W mieście, w którym opinia rozchodzi się szybciej niż algorytm, recenzje pracują na czterech osobnych poziomach. Jak zbierać je zgodnie z zaostrzonymi zasadami z 2026 roku i dlaczego równy napływ bije jednorazowy skok.",
    category: "SEO",
    date: "2026-08-07",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-ostrowiec-swietokrzyski.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-swidnica",
    title: "Pozycjonowanie wizytówki Google Świdnica",
    excerpt:
      "W Świdnicy odległości są małe, więc o zleceniu decyduje nie tylko pozycja, ale i to, jak profil wygląda w wynikach. Rozkładamy wynik z trójki na części pierwsze i pokazujemy, które zdjęcia faktycznie zwiększają liczbę kliknięć.",
    category: "SEO",
    date: "2026-08-08",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-swidnica.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-zamosc",
    title: "Pozycjonowanie wizytówki Google Zamość",
    excerpt:
      "Zamość łączy rynek lokalny z ruchem turystycznym, a coraz większa część zapytań kończy się odpowiedzią wygenerowaną przez model AI. Skąd taki model bierze informacje o Twojej firmie i jak zadbać, żeby brał je z Twoich źródeł.",
    category: "SEO",
    date: "2026-08-09",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-zamosc.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-mielec",
    title: "Pozycjonowanie wizytówki Google Mielec",
    excerpt:
      "Mielec to strefa ekonomiczna, lotnictwo i podwykonawcy, czyli klient, który nie szuka pod wpływem pilnej potrzeby. Czy firma B2B w ogóle potrzebuje profilu w Google, jaką ustawić kategorię i co wpisać w usługi bez cennika.",
    category: "SEO",
    date: "2026-08-10",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-mielec.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-elk",
    title: "Pozycjonowanie wizytówki Google Ełk",
    excerpt:
      "Ełk ma 2825 osób na kilometr kwadratowy, czyli gęstość porównywalną z dużym miastem przy dziesięciokrotnie mniejszym rynku. Rozpisujemy wdrożenie profilu firmy na siedem dni: co zrobić którego dnia, ile to zajmuje i czego nie robić w pierwszym tygodniu.",
    category: "SEO",
    date: "2026-07-01",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-elk.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-leszno",
    title: "Pozycjonowanie wizytówki Google Leszno",
    excerpt:
      "Dopisanie miasta do nazwy firmy podnosi pozycję i jest naruszeniem wytycznych. Co dokładnie wolno w polu nazwy, czym kończy się kreatywność i jak zgłosić konkurenta, który tę granicę przekroczył.",
    category: "SEO",
    date: "2026-07-02",
    readTime: 10,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-leszno.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-gniezno",
    title: "Pozycjonowanie wizytówki Google Gniezno",
    excerpt:
      "Google patrzy na historię profilu, więc pięcioletni wpis startuje z innego miejsca niż założony wczoraj. Co zrobić, gdy Twoja firma ma stary, zapomniany profil dodany przez kogoś innego, i jak go odzyskać zamiast zakładać nowy.",
    category: "SEO",
    date: "2026-07-03",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-gniezno.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-ostrow-wielkopolski",
    title: "Pozycjonowanie wizytówki Google Ostrów Wielkopolski",
    excerpt:
      "Profil i strona firmowa potrafią walczyć o tę samą frazę i nawzajem się osłabiać. Jak rozdzielić role, żeby profil brał zapytania z Map, a strona zapytania z nazwą miejscowości, zamiast konkurować ze sobą.",
    category: "SEO",
    date: "2026-07-04",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-ostrow-wielkopolski.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-krosno",
    title: "Pozycjonowanie wizytówki Google Krosno",
    excerpt:
      "W Krośnie odległość w linii prostej myli, bo teren jest pofałdowany, a dojazd rzadko biegnie prosto. Jak ustawić pinezkę, opisać dojazd i dobrać obszar obsługi tam, gdzie mapa nie pokrywa się z rzeczywistością.",
    category: "SEO",
    date: "2026-07-05",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-krosno.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-stalowa-wola",
    title: "Pozycjonowanie wizytówki Google Stalowa Wola",
    excerpt:
      "Przeprowadzka firmy to moment, w którym najłatwiej stracić dorobek profilu. Kolejność działań przy zmianie adresu, czego nie robić w trakcie i dlaczego zakładanie nowego profilu jest najgorszą z możliwych decyzji.",
    category: "SEO",
    date: "2026-07-06",
    readTime: 10,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-stalowa-wola.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-chelm",
    title: "Pozycjonowanie wizytówki Google Chełm",
    excerpt:
      "Chełm leży kilkadziesiąt kilometrów od granicy, więc część zapytań przychodzi w innym języku. Jak ustawić profil, żeby obsługiwał obie grupy klientów, i co zrobić z opiniami napisanymi po ukraińsku.",
    category: "SEO",
    date: "2026-07-07",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-chelm.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-biala-podlaska",
    title: "Pozycjonowanie wizytówki Google Biała Podlaska",
    excerpt:
      "Wiadomości w profilu to kanał, który większość firm ma włączony i nieobsługiwany. Jak działa czas odpowiedzi, co się dzieje po jego przekroczeniu i kiedy lepiej ten kanał wyłączyć niż prowadzić go źle.",
    category: "SEO",
    date: "2026-07-08",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-biala-podlaska.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-skierniewice",
    title: "Pozycjonowanie wizytówki Google Skierniewice",
    excerpt:
      "Kiedy wystarczy dopracowany profil, a kiedy trzeba dopłacić do reklamy. Rozkładamy oba narzędzia na czynniki: co dają, ile kosztują, w jakiej kolejności je uruchamiać i czego reklama nie naprawi.",
    category: "SEO",
    date: "2026-07-09",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-skierniewice.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-tomaszow-mazowiecki",
    title: "Pozycjonowanie wizytówki Google Tomaszów Mazowiecki",
    excerpt:
      "Profil spadł z pierwszej trójki i nie wiadomo dlaczego. Lista kontrolna w kolejności od najczęstszych przyczyn: zmiana w profilu, zgłoszenie konkurenta, nowy gracz na rynku, aktualizacja algorytmu i awaria po Twojej stronie.",
    category: "SEO",
    date: "2026-07-10",
    readTime: 10,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-tomaszow-mazowiecki.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-pabianice",
    title: "Pozycjonowanie wizytówki Google Pabianice",
    excerpt:
      "Profil i strona odpowiadają za zupełnie inne rodzaje zapytań i nie zastępują się nawzajem. Rozpisujemy, które zapytanie trafia gdzie, co z tego wynika dla firmy z Pabianic i gdzie zaczyna się granica możliwości profilu.",
    category: "SEO",
    date: "2026-07-11",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-pabianice.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-kolobrzeg",
    title: "Pozycjonowanie wizytówki Google Kołobrzeg",
    excerpt:
      "Zdjęcia dodane przez klientów pojawiają się w profilu bez Twojej zgody i często to one wyświetlają się jako pierwsze. Co da się z nimi zrobić, czego nie da się usunąć i jak przewagą liczebną własnych zdjęć odsunąć te niechciane.",
    category: "SEO",
    date: "2026-07-12",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-kolobrzeg.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-szczecinek",
    title: "Pozycjonowanie wizytówki Google Szczecinek",
    excerpt:
      "Sieciowa firma z profilem w każdym mieście ma przewagi, których lokalna firma nie skopiuje. Ma też słabości, których nie da się naprawić z centrali. Cztery miejsca, w których jednoosobowa firma ze Szczecinka wygrywa z siecią.",
    category: "SEO",
    date: "2026-07-13",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-szczecinek.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-swinoujscie",
    title: "Pozycjonowanie wizytówki Google Świnoujście",
    excerpt:
      "Świnoujście leży na wyspach, a dojazd wymaga przeprawy, przez co odległość w linii prostej nie mówi nic o realnym czasie dojazdu. Jak opisać taki dojazd w profilu i na stronie, żeby klient nie odpadł na etapie mapy.",
    category: "SEO",
    date: "2026-07-14",
    readTime: 10,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-swinoujscie.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-grudziadz",
    title: "Pozycjonowanie wizytówki Google Grudziądz",
    excerpt:
      "Cytowania NAP i linki do profilu to temat, wokół którego narosło najwięcej mitów. Co realnie działa, co jest neutralne, co potrafi zaszkodzić i dlaczego dwadzieścia spójnych wpisów bije dwieście przypadkowych.",
    category: "SEO",
    date: "2026-07-15",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-grudziadz.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-wloclawek",
    title: "Pozycjonowanie wizytówki Google Włocławek",
    excerpt:
      "Zawieszenie profilu odcina firmę od Map z dnia na dzień, razem ze wszystkimi opiniami. Najczęstsze przyczyny, przebieg procedury odwoławczej krok po kroku i czego nie robić w trakcie, żeby nie pogorszyć sprawy.",
    category: "SEO",
    date: "2026-07-16",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-wloclawek.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-starogard-gdanski",
    title: "Pozycjonowanie wizytówki Google Starogard Gdański",
    excerpt:
      "Firma robi kilka różnych rzeczy i pojawia się pytanie, czy założyć osobne profile. Kiedy Google na to pozwala, kiedy uzna to za naruszenie i co zrobić zamiast tego, gdy usługi naprawdę są od siebie odległe.",
    category: "SEO",
    date: "2026-07-17",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-starogard-gdanski.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-tczew",
    title: "Pozycjonowanie wizytówki Google Tczew",
    excerpt:
      "Statystyki profilu pokazują wyświetlenia, telefony i kliknięcia, ale bez oznaczeń UTM nie wiadomo, co z tego przeszło na stronę. Jak zbudować prosty pomiar, którego nie trzeba obsługiwać codziennie.",
    category: "SEO",
    date: "2026-07-18",
    readTime: 10,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-tczew.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-wejherowo",
    title: "Pozycjonowanie wizytówki Google Wejherowo",
    excerpt:
      "Utrata dostępu do profilu firmy zdarza się częściej, niż się wydaje, i zwykle przez pracownika, który odszedł. Jak rozdzielić role właściciela i menedżera, co sprawdzić dziś i jak przygotować się na odejście osoby z dostępem.",
    category: "SEO",
    date: "2026-07-19",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-wejherowo.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-nysa",
    title: "Pozycjonowanie wizytówki Google Nysa",
    excerpt:
      "Lokal w galerii albo w pasażu to najtrudniejszy przypadek dla pinezki, bo pod jednym adresem działa kilkadziesiąt firm. Jak ustawić lokalizację, opisać wejście i piętro oraz czego nie wpisywać w pole adresu.",
    category: "SEO",
    date: "2026-07-20",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-nysa.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-kedzierzyn-kozle",
    title: "Pozycjonowanie wizytówki Google Kędzierzyn-Koźle",
    excerpt:
      "Nie każda fraza jest warta walki. Jak w kilkanaście minut ocenić, czy zapytanie ma wystarczający wolumen i na tyle słabą konkurencję, żeby wejście do pierwszej trójki było realne w kilka miesięcy.",
    category: "SEO",
    date: "2026-07-21",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-kedzierzyn-kozle.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-jelenia-gora",
    title: "Pozycjonowanie wizytówki Google Jelenia Góra",
    excerpt:
      "Ruch turystyczny oznacza opinie po niemiecku, czesku i angielsku. Czy odpowiadać w języku opinii, jak działa automatyczne tłumaczenie, co zrobić z oceną bez treści i jak z tego zbudować przewagę.",
    category: "SEO",
    date: "2026-07-22",
    readTime: 10,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-jelenia-gora.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-lubin",
    title: "Pozycjonowanie wizytówki Google Lubin",
    excerpt:
      "Profil firmy w Google jest pierwszym miejscem, które sprawdza kandydat do pracy, a nie tylko klient. Co zobaczy, jak to wykorzystać przy rekrutacji i dlaczego opinie pracowników trafiają tam, gdzie widzą je klienci.",
    category: "SEO",
    date: "2026-07-23",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-lubin.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-glogow",
    title: "Pozycjonowanie wizytówki Google Głogów",
    excerpt:
      "Duplikaty profilu rozdzielają opinie, mieszają dane i osłabiają obie kopie naraz. Skąd się biorą, jak je wykryć w kilka minut i jaka jest poprawna procedura scalania, żeby nie stracić historii.",
    category: "SEO",
    date: "2026-07-24",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-glogow.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-nowy-sacz",
    title: "Pozycjonowanie wizytówki Google Nowy Sącz",
    excerpt:
      "Sam profil ma sufit, o który prędzej czy później uderzysz. Jaka treść na stronie realnie go podnosi, ile jej potrzeba, w jakiej kolejności ją budować i które podstrony nie robią nic poza zajmowaniem miejsca.",
    category: "SEO",
    date: "2026-07-25",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-nowy-sacz.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-oswiecim",
    title: "Pozycjonowanie wizytówki Google Oświęcim",
    excerpt:
      "Atrybuty to najszybciej wypełniana i najczęściej pomijana sekcja profilu. Które z nich realnie zmieniają decyzję klienta, które są tylko informacją i dlaczego w mieście z ruchem turystycznym warto uzupełnić komplet.",
    category: "SEO",
    date: "2026-07-26",
    readTime: 10,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-oswiecim.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-raciborz",
    title: "Pozycjonowanie wizytówki Google Racibórz",
    excerpt:
      "Posty nie podnoszą pozycji i to trzeba powiedzieć wprost. Do czego więc służą, które formaty klikają się najlepiej, jak długo żyją i ile ich publikować, żeby nie robić pracy bez zwrotu.",
    category: "SEO",
    date: "2026-07-27",
    readTime: 11,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-raciborz.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-zory",
    title: "Pozycjonowanie wizytówki Google Żory",
    excerpt:
      "Jedna osoba, brak lokalu, brak pracowników i pytanie, czy profil w ogóle ma sens. Ma, ale prowadzi się go inaczej: krótsza lista usług, inne godziny, inne zdjęcia i inne podejście do obszaru obsługi.",
    category: "SEO",
    date: "2026-07-28",
    readTime: 12,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-zory.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-ostroleka",
    title: "Pozycjonowanie wizytówki Google Ostrołęka",
    excerpt:
      "Weryfikacja nagraniem wideo to dziś najczęstsza droga potwierdzenia firmy i najczęstsze miejsce odrzucenia. Co dokładnie trzeba pokazać w nagraniu, w jakiej kolejności i przez co profile wracają do poprawki.",
    category: "SEO",
    date: "2026-07-29",
    readTime: 9,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-ostroleka.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-lomza",
    title: "Pozycjonowanie wizytówki Google Łomża",
    excerpt:
      "Ile z pozycjonowania profilu da się zrobić samodzielnie za zero złotych, a gdzie zaczyna się granica, za którą płatna pomoc realnie się zwraca. Rozliczamy to na konkretach zamiast na obietnicach.",
    category: "SEO",
    date: "2026-07-30",
    readTime: 10,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-lomza.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-legnica",
    title: "Pozycjonowanie wizytówki Google Legnica",
    excerpt:
      "Profil konkurenta jest w całości jawny i można go rozłożyć na czynniki w kwadrans. Pokazujemy, na co dokładnie patrzeć, czego nie da się z niego odczytać i które ustalenia wolno przenieść do siebie, a które są naruszeniem.",
    category: "SEO",
    date: "2026-06-01",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-legnica.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-boleslawiec",
    title: "Pozycjonowanie wizytówki Google Bolesławiec",
    excerpt:
      "Firma sprzedaje w całym kraju, ale profil działa wyłącznie lokalnie i nie da się tego obejść. Jak ustawić profil, żeby obsługiwał rynek lokalny, i którymi narzędziami budować sprzedaż poza miastem.",
    category: "SEO",
    date: "2026-06-02",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-boleslawiec.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-kalisz",
    title: "Pozycjonowanie wizytówki Google Kalisz",
    excerpt:
      "Zdjęcie budynku od strony ulicy w Mapach nie pochodzi od Ciebie i często jest sprzed lat. Co da się z nim zrobić, jak zgłosić rozmycie i dlaczego własne zdjęcie wejścia jest ważniejsze niż panorama.",
    category: "SEO",
    date: "2026-06-03",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-kalisz.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-wrzesnia",
    title: "Pozycjonowanie wizytówki Google Września",
    excerpt:
      "Zapytania z dopiskiem w pobliżu i filtr otwarte teraz działają inaczej niż zwykłe wyszukiwanie i premiują zupełnie inne ustawienia profilu. Rozkładamy oba mechanizmy i pokazujemy, co pod nie ustawić.",
    category: "SEO",
    date: "2026-06-04",
    readTime: 17,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-wrzesnia.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-tarnow",
    title: "Pozycjonowanie wizytówki Google Tarnów",
    excerpt:
      "Pod wynikiem firmy Google potrafi dokleić fragment opinii albo nazwę usługi jako uzasadnienie trafności. Skąd bierze te fragmenty, dlaczego jednym firmom je pokazuje, a innym nie, i jak zwiększyć swoje szanse.",
    category: "SEO",
    date: "2026-06-05",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-tarnow.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-chrzanow",
    title: "Pozycjonowanie wizytówki Google Chrzanów",
    excerpt:
      "W powiecie chrzanowskim kilka miast leży obok siebie i klienci mieszają ich nazwy w zapytaniach. Jak ustawić profil i treść na stronie, żeby nie przegrywać zapytań z nazwą sąsiedniej miejscowości.",
    category: "SEO",
    date: "2026-06-06",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-chrzanow.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-przemysl",
    title: "Pozycjonowanie wizytówki Google Przemyśl",
    excerpt:
      "Co robić, gdy Twoja usługa ma kilkadziesiąt zapytań miesięcznie w całym mieście. Jak wtedy liczyć opłacalność, na czym się skupić i dlaczego standardowe poradniki pisane pod duże rynki tu zawodzą.",
    category: "SEO",
    date: "2026-06-07",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-przemysl.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-debica",
    title: "Pozycjonowanie wizytówki Google Dębica",
    excerpt:
      "Dębica leży przy trasie tranzytowej, więc część klientów to osoby przejazdem, które nie wrócą. Jak ustawić profil pod taki ruch, czego od niego nie oczekiwać i jak nie zepsuć sobie rynku lokalnego.",
    category: "SEO",
    date: "2026-06-08",
    readTime: 17,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-debica.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-pulawy",
    title: "Pozycjonowanie wizytówki Google Puławy",
    excerpt:
      "Nowa firma startuje z zerem opinii, zerem zdjęć i zerem historii, a obok stoją profile prowadzone od lat. Realny plan na pierwsze trzy miesiące, z tym, czego w tym czasie nie da się przyspieszyć.",
    category: "SEO",
    date: "2026-06-09",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-pulawy.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-swidnik",
    title: "Pozycjonowanie wizytówki Google Świdnik",
    excerpt:
      "Coraz więcej zapytań lokalnych pada głosem, w samochodzie i przez asystenta, a te zapytania brzmią inaczej niż wpisywane z klawiatury. Co to zmienia w ustawieniach profilu i w nazwach usług.",
    category: "SEO",
    date: "2026-06-10",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-swidnik.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-belchatow",
    title: "Pozycjonowanie wizytówki Google Bełchatów",
    excerpt:
      "Praca zmianowa, dyżury i całodobowa dostępność to najczęstsze źródło błędnych godzin w profilu. Jak zapisać nietypowy grafik, żeby zgadzał się z rzeczywistością i nie kosztował Cię ocen jednogwiazdkowych.",
    category: "SEO",
    date: "2026-06-11",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-belchatow.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-sieradz",
    title: "Pozycjonowanie wizytówki Google Sieradz",
    excerpt:
      "Podpowiedzi wyszukiwarki pokazują, czego ludzie faktycznie szukają, a przy nazwie firmy potrafią doklejać słowa, których nie chcesz. Skąd się biorą, co da się z nimi zrobić i jak czytać je jako darmowe źródło danych.",
    category: "SEO",
    date: "2026-06-12",
    readTime: 17,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-sieradz.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-kutno",
    title: "Pozycjonowanie wizytówki Google Kutno",
    excerpt:
      "Kutno obsługuje klientów z całego regionu dzięki położeniu przy węźle, ale profil widzi tylko to, co blisko. Jak rozdzielić pracę między profil a stronę, gdy Twoi klienci przyjeżdżają z daleka.",
    category: "SEO",
    date: "2026-06-13",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-kutno.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-plock",
    title: "Pozycjonowanie wizytówki Google Płock",
    excerpt:
      "Duży zakład, teren przemysłowy albo obiekt z kilkoma wejściami to przypadek, którego profil nie obsługuje wprost. Gdzie postawić pinezkę, jak opisać wjazdy dla dostaw i kiedy uzasadniony jest drugi wpis.",
    category: "SEO",
    date: "2026-06-14",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-plock.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-ciechanow",
    title: "Pozycjonowanie wizytówki Google Ciechanów",
    excerpt:
      "Ile realnie trwa wejście do pierwszej trójki i jak wygląda krzywa efektów miesiąc po miesiącu. Rozkładamy typowy przebieg na etapy, z tym, co widać po tygodniu, po kwartale i po roku.",
    category: "SEO",
    date: "2026-06-15",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-ciechanow.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-minsk-mazowiecki",
    title: "Pozycjonowanie wizytówki Google Mińsk Mazowiecki",
    excerpt:
      "Duża część mieszkańców Mińska pracuje w Warszawie i wpisuje zapytania stamtąd, a Twój profil ich wtedy nie widzi. Co z tym zrobić i jak przechwycić klienta, który szuka poza własnym miastem.",
    category: "SEO",
    date: "2026-06-16",
    readTime: 17,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-minsk-mazowiecki.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-chojnice",
    title: "Pozycjonowanie wizytówki Google Chojnice",
    excerpt:
      "W miejscowościach z ruchem weekendowym profil pracuje w rytmie tygodnia, nie roku. Jak ustawić godziny, posty i obsadę pod piątek i sobotę oraz co zmienić w profilu poza sezonem.",
    category: "SEO",
    date: "2026-06-17",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-chojnice.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-kwidzyn",
    title: "Pozycjonowanie wizytówki Google Kwidzyn",
    excerpt:
      "Błędne godziny, obcy numer telefonu albo etykieta zamknięte na stałe potrafią pojawić się w profilu bez Twojej wiedzy. Skąd się biorą takie zmiany, jak je szybko cofnąć i jak zabezpieczyć się na przyszłość.",
    category: "SEO",
    date: "2026-06-18",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-kwidzyn.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-malbork",
    title: "Pozycjonowanie wizytówki Google Malbork",
    excerpt:
      "Gdy w mieście jest jeden obiekt, którego szukają wszyscy, reszta firm walczy o resztki uwagi. Jak zbudować widoczność obok dominującej atrakcji i jak przechwycić ruch turystyczny bez naciągania profilu.",
    category: "SEO",
    date: "2026-06-19",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-malbork.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-elblag",
    title: "Pozycjonowanie wizytówki Google Elbląg",
    excerpt:
      "Zapytania o nazwę Twojej firmy to osobna kategoria wyników, w której profil, panel wiedzy i strona pokazują się razem. Jak zapanować nad tym, co widzi klient, który już Cię zna z polecenia.",
    category: "SEO",
    date: "2026-06-20",
    readTime: 17,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-elblag.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-ilawa",
    title: "Pozycjonowanie wizytówki Google Iława",
    excerpt:
      "Przycisk rezerwacji potrafi zmienić profil z wizytówki w kanał sprzedaży, ale tylko wtedy, gdy stoi za nim działający system. Kiedy warto go podpiąć, kiedy zaszkodzi i jak przygotować się na sezon.",
    category: "SEO",
    date: "2026-06-21",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-ilawa.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-gorzow-wielkopolski",
    title: "Pozycjonowanie wizytówki Google Gorzów Wielkopolski",
    excerpt:
      "Ten sam profil wygląda inaczej na telefonie i na komputerze, a większość zapytań lokalnych pada z telefonu. Co jest widoczne na małym ekranie, co się chowa i które elementy warto pod to dopasować.",
    category: "SEO",
    date: "2026-06-22",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-gorzow-wielkopolski.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-nowa-sol",
    title: "Pozycjonowanie wizytówki Google Nowa Sól",
    excerpt:
      "Sprzedaż firmy, zmiana wspólnika albo przejęcie działalności to moment, w którym najłatwiej stracić profil razem z opiniami. Jak przenieść go poprawnie i czego nie wolno zrobić po drodze.",
    category: "SEO",
    date: "2026-06-23",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-nowa-sol.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-brzeg",
    title: "Pozycjonowanie wizytówki Google Brzeg",
    excerpt:
      "Podawać ceny w profilu czy nie. Rozkładamy argumenty na obie strony, pokazujemy, gdzie cena realnie pomaga, gdzie odcina zapytania i jak zapisać widełki, żeby nie związać sobie rąk.",
    category: "SEO",
    date: "2026-06-24",
    readTime: 17,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-brzeg.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-tarnowskie-gory",
    title: "Pozycjonowanie wizytówki Google Tarnowskie Góry",
    excerpt:
      "W konurbacji granice miast są umowne, a klienci ich nie rozróżniają. Jak ustawić profil i treść, gdy sąsiednie miasta zlewają się w jeden organizm, i dlaczego promień zasięgu jest tu złym narzędziem.",
    category: "SEO",
    date: "2026-06-25",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-tarnowskie-gory.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-zawiercie",
    title: "Pozycjonowanie wizytówki Google Zawiercie",
    excerpt:
      "Awaria, usterka i sytuacja pilna to zupełnie inny typ zapytania niż planowany zakup usługi. Jak przygotować profil pod klienta, który potrzebuje teraz, i co decyduje o wyborze w takiej chwili.",
    category: "SEO",
    date: "2026-06-26",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-zawiercie.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-cieszyn",
    title: "Pozycjonowanie wizytówki Google Cieszyn",
    excerpt:
      "Miasto podzielone granicą oznacza dwie waluty, dwa numery kierunkowe i dwa zestawy oczekiwań. Jak poprowadzić jeden profil dla klientów z obu stron i gdzie przebiega granica tego, co wolno.",
    category: "SEO",
    date: "2026-06-27",
    readTime: 16,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-cieszyn.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-starachowice",
    title: "Pozycjonowanie wizytówki Google Starachowice",
    excerpt:
      "Firma zmienia to, czym się zajmuje, a profil dalej opisuje poprzednią działalność i przyciąga niewłaściwe zapytania. Jak przeprowadzić taką zmianę bez utraty historii i bez ryzyka zawieszenia.",
    category: "SEO",
    date: "2026-06-28",
    readTime: 17,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-starachowice.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-koszalin",
    title: "Pozycjonowanie wizytówki Google Koszalin",
    excerpt:
      "Nad wynikami lokalnymi często stoją rankingi, katalogi i porównywarki, które przechwytują zapytania zanim dotrą do firm. Jak z nimi konkurować i kiedy lepiej być w nich obecnym niż z nimi walczyć.",
    category: "SEO",
    date: "2026-06-29",
    readTime: 14,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-koszalin.svg",
    published: true,
    pinBottom: true,
  },
  {
    slug: "pozycjonowanie-wizytowki-google-brodnica",
    title: "Pozycjonowanie wizytówki Google Brodnica",
    excerpt:
      "Przychodzi moment, w którym profil jest kompletny i dalsze zmiany nic nie dają. Jak rozpoznać ten sufit, czego wtedy nie robić i gdzie przenieść wysiłek, żeby nadal rosnąć.",
    category: "SEO",
    date: "2026-06-30",
    readTime: 15,
    coverColor: "#FF6A00",
    coverImage: "/blog/cover-brodnica.svg",
    published: true,
    pinBottom: true,
  },
];

// Ludność miast serii lokalizacyjnej w tysiącach, wartości przybliżone.
// Służy wyłącznie do grupowania wpisów na /blog, nie jest nigdzie wyświetlana.
// Miasto spoza mapy trafia do najniższego przedziału.
export const cityPopulation: Record<string, number> = {
  "pozycjonowanie-wizytowki-google-warszawa": 1860,
  "pozycjonowanie-wizytowki-google-krakow": 809,
  "pozycjonowanie-wizytowki-google-wroclaw": 673,
  "pozycjonowanie-wizytowki-google-lodz": 646,
  "pozycjonowanie-wizytowki-google-poznan": 536,
  "pozycjonowanie-wizytowki-google-gdansk": 488,
  "pozycjonowanie-wizytowki-google-szczecin": 388,
  "pozycjonowanie-wizytowki-google-lublin": 329,
  "pozycjonowanie-wizytowki-google-bydgoszcz": 325,
  "pozycjonowanie-wizytowki-google-bialystok": 290,
  "pozycjonowanie-wizytowki-google-katowice": 279,
  "pozycjonowanie-wizytowki-google-gdynia": 243,
  "pozycjonowanie-wizytowki-google-czestochowa": 208,
  "pozycjonowanie-wizytowki-google-radom": 198,
  "pozycjonowanie-wizytowki-google-rzeszow": 197,
  "pozycjonowanie-wizytowki-google-torun": 195,
  "pozycjonowanie-wizytowki-google-sosnowiec": 189,
  "pozycjonowanie-wizytowki-google-kielce": 184,
  "pozycjonowanie-wizytowki-google-gliwice": 171,
  "pozycjonowanie-wizytowki-google-olsztyn": 168,
  "pozycjonowanie-wizytowki-google-bielsko-biala": 167,
  "pozycjonowanie-wizytowki-google-zabrze": 154,
  "pozycjonowanie-wizytowki-google-bytom": 149,
  "pozycjonowanie-wizytowki-google-zielona-gora": 139,
  "pozycjonowanie-wizytowki-google-rybnik": 134,
  "pozycjonowanie-wizytowki-google-ruda-slaska": 132,
  "pozycjonowanie-wizytowki-google-opole": 127,
  "pozycjonowanie-wizytowki-google-tychy": 122,
  "pozycjonowanie-wizytowki-google-gorzow-wielkopolski": 119,
  "pozycjonowanie-wizytowki-google-elblag": 114,
  "pozycjonowanie-wizytowki-google-dabrowa-gornicza": 114,
  "pozycjonowanie-wizytowki-google-plock": 113,
  "pozycjonowanie-wizytowki-google-wloclawek": 106,
  "pozycjonowanie-wizytowki-google-koszalin": 104,
  "pozycjonowanie-wizytowki-google-tarnow": 103,
  "pozycjonowanie-wizytowki-google-kalisz": 96,
  "pozycjonowanie-wizytowki-google-legnica": 96,
  "pozycjonowanie-wizytowki-google-grudziadz": 91,
  "pozycjonowanie-wizytowki-google-nowy-sacz": 82,
  "pozycjonowanie-wizytowki-google-jelenia-gora": 76,
  "pozycjonowanie-wizytowki-google-siedlce": 76,
  "pozycjonowanie-wizytowki-google-pila": 71,
  "pozycjonowanie-wizytowki-google-inowroclaw": 71,
  "pozycjonowanie-wizytowki-google-konin": 70,
  "pozycjonowanie-wizytowki-google-piotrkow-trybunalski": 70,
  "pozycjonowanie-wizytowki-google-ostrow-wielkopolski": 70,
  "pozycjonowanie-wizytowki-google-lubin": 70,
  "pozycjonowanie-wizytowki-google-suwalki": 68,
  "pozycjonowanie-wizytowki-google-stargard": 66,
  "pozycjonowanie-wizytowki-google-gniezno": 66,
  "pozycjonowanie-wizytowki-google-glogow": 64,
  "pozycjonowanie-wizytowki-google-ostrowiec-swietokrzyski": 63,
  "pozycjonowanie-wizytowki-google-leszno": 62,
  "pozycjonowanie-wizytowki-google-elk": 62,
  "pozycjonowanie-wizytowki-google-zory": 61,
  "pozycjonowanie-wizytowki-google-zamosc": 60,
  "pozycjonowanie-wizytowki-google-pabianice": 60,
  "pozycjonowanie-wizytowki-google-tomaszow-mazowiecki": 60,
  "pozycjonowanie-wizytowki-google-lomza": 60,
  "pozycjonowanie-wizytowki-google-tarnowskie-gory": 60,
  "pozycjonowanie-wizytowki-google-mielec": 59,
  "pozycjonowanie-wizytowki-google-tczew": 59,
  "pozycjonowanie-wizytowki-google-chelm": 58,
  "pozycjonowanie-wizytowki-google-kedzierzyn-kozle": 58,
  "pozycjonowanie-wizytowki-google-stalowa-wola": 57,
  "pozycjonowanie-wizytowki-google-przemysl": 57,
  "pozycjonowanie-wizytowki-google-belchatow": 56,
  "pozycjonowanie-wizytowki-google-swidnica": 55,
  "pozycjonowanie-wizytowki-google-biala-podlaska": 55,
  "pozycjonowanie-wizytowki-google-raciborz": 53,
  "pozycjonowanie-wizytowki-google-ostroleka": 51,
  "pozycjonowanie-wizytowki-google-wejherowo": 49,
  "pozycjonowanie-wizytowki-google-zawiercie": 48,
  "pozycjonowanie-wizytowki-google-starachowice": 48,
  "pozycjonowanie-wizytowki-google-starogard-gdanski": 47,
  "pozycjonowanie-wizytowki-google-skierniewice": 46,
  "pozycjonowanie-wizytowki-google-pulawy": 46,
  "pozycjonowanie-wizytowki-google-kolobrzeg": 45,
  "pozycjonowanie-wizytowki-google-debica": 45,
  "pozycjonowanie-wizytowki-google-krosno": 45,
  "pozycjonowanie-wizytowki-google-ciechanow": 43,
  "pozycjonowanie-wizytowki-google-nysa": 42,
  "pozycjonowanie-wizytowki-google-kutno": 42,
  "pozycjonowanie-wizytowki-google-sieradz": 41,
  "pozycjonowanie-wizytowki-google-minsk-mazowiecki": 41,
  "pozycjonowanie-wizytowki-google-swinoujscie": 40,
  "pozycjonowanie-wizytowki-google-szczecinek": 39,
  "pozycjonowanie-wizytowki-google-swidnik": 39,
  "pozycjonowanie-wizytowki-google-chojnice": 39,
  "pozycjonowanie-wizytowki-google-boleslawiec": 38,
  "pozycjonowanie-wizytowki-google-nowa-sol": 38,
  "pozycjonowanie-wizytowki-google-kwidzyn": 37,
  "pozycjonowanie-wizytowki-google-malbork": 37,
  "pozycjonowanie-wizytowki-google-chrzanow": 35,
  "pozycjonowanie-wizytowki-google-oswiecim": 34,
  "pozycjonowanie-wizytowki-google-brzeg": 34,
  "pozycjonowanie-wizytowki-google-cieszyn": 34,
  "pozycjonowanie-wizytowki-google-ilawa": 33,
  "pozycjonowanie-wizytowki-google-wrzesnia": 30,
  "pozycjonowanie-wizytowki-google-brodnica": 28,
};

// Przedziały wielkości miast dla serii lokalizacyjnej na /blog.
// `min` w tysiącach mieszkańców, sprawdzane od góry.
export const cityTiers = [
  { min: 500, label: "Miasta powyżej 500 tys. mieszkańców" },
  { min: 250, label: "Miasta od 250 do 499 tys. mieszkańców" },
  { min: 100, label: "Miasta od 100 do 249 tys. mieszkańców" },
  { min: 0,   label: "Miasta poniżej 100 tys. mieszkańców" },
] as const;

// Nazwa miejscowości wyciągnięta z tytułu wpisu lokalizacyjnego.
export function cityNameFromTitle(title: string): string {
  return title
    .replace(/^Pozycjonowanie wizytówki Google\s*/i, "")
    .split(/\s+[–—-]\s+/)[0]
    .trim();
}

export function getPublishedPosts(): Post[] {
  return posts
    .filter((p) => p.published && !p.hideFromBlog)
    .sort(
      (a, b) =>
        Number(a.pinBottom ?? false) - Number(b.pinBottom ?? false) ||
        b.date.localeCompare(a.date),
    );
}

// Najpopularniejsze wpisy — oznaczone flagą `popular`, fallback do najnowszych.
export function getPopularPosts(limit = 3): Post[] {
  const published = posts.filter((p) => p.published && !p.hideFromBlog);
  const popular = published.filter((p) => p.popular);
  const rest = published
    .filter((p) => !p.popular)
    .sort((a, b) => b.date.localeCompare(a.date));
  return [...popular, ...rest].slice(0, limit);
}

export function getPostBySlug(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug && p.published);
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("pl-PL", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}
